-- Create and Select Database
CREATE DATABASE IF NOT EXISTS TopDeckCardShop;
USE TopDeckCardShop;

-- Create User and Assign Permissions
CREATE USER IF NOT EXISTS 'manager_mark'@'localhost' IDENTIFIED BY 'password123';
GRANT ALL PRIVILEGES ON TopDeckCardShop.* TO 'manager_mark'@'localhost';
FLUSH PRIVILEGES;

-- Create Independent Tables
CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_FNAME VARCHAR(45) NOT NULL,
    CUSTOMER_LNAME VARCHAR(45),
    CUSTOMER_EMAIL VARCHAR(45),
    CUSTOMER_PHONE VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS LOCATION (
    LOCATION_ID INT PRIMARY KEY,
    LOCATION_ADDRESS VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(45) NOT NULL,
    PRODUCT_PRICEBOUGHT DECIMAL(5,2) NOT NULL,
    PRODUCT_PRICELISTED DECIMAL(5,2) NOT NULL,
    PRODUCT_STOCK INT NOT NULL
);

-- Create Tables with Dependencies
CREATE TABLE IF NOT EXISTS CASHIER (
    CASHIER_ID INT PRIMARY KEY,
    CASHIER_WAGE DECIMAL(5,2) NOT NULL,
    CASHIER_HOURSWORKED INT,
    CUSTOMER_ID INT,
    LOCATION_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);

CREATE TABLE IF NOT EXISTS MANAGER (
    MANAGER_ID INT PRIMARY KEY,
    MANAGER_WAGE DECIMAL(5,2) NOT NULL,
    MANAGER_HOURSWORKED INT,
    CUSTOMER_ID INT,
    LOCATION_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);

CREATE TABLE IF NOT EXISTS CHECKOUT (
    CHECKOUT_ID INT PRIMARY KEY,
    CHECKOUT_TOTAL_PRICE FLOAT NOT NULL,
    CHECKOUT_DATE DATE NOT NULL,
    CASHIER_ID INT,
    CUSTOMER_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (CASHIER_ID) REFERENCES CASHIER(CASHIER_ID)
);

CREATE TABLE IF NOT EXISTS PURCHASES (
    PURCHASES_ID INT PRIMARY KEY,
    PURCHASES_QUANTITY INT NOT NULL,
    PRODUCT_ID INT,
    CHECKOUT_ID INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (CHECKOUT_ID) REFERENCES CHECKOUT(CHECKOUT_ID)
);
